### ISSUE TITLE
 looking for a way to run your software and some issues 

### ISSUE THREAD

**Issue by mx202** [salemebo/Ariafx#1]
Hello

I would like to tell you that your program according to the mentioned specifications and the beautiful modern design shown in the screenshots is the best download program I have reviewed so far, so I would like to thank you for your effort and great creativity.

On the other hand, it seems that there is no clear way to operate it and use it. Please tell us how.

Also you mentioned that it is compatible and supports FlashGot for Firefox but this plugin no longer supports Firefox anymore.
So please provide another solution

As for Chrome, the Aria Port has not been updated and has not been supported since 2014

I am very looking forward to using the program and it would be very nice to allow us to donate in support of you

I'm waiting for your answer and thank you

**Comment by muhammad-salem** [comment]
Thank you for your feedback.

# how to use Ariafx App:
-  download the jar file  [ariafx-0.28.9-jar-with-dependencies.jar](https://github.com/salemebo/Ariafx/releases/download/0.28.9/ariafx-0.28.9-jar-with-dependencies.jar)
- make sure that you have JDK 8 installed on your system and it is the default JVM on your OS.
- run jar file with this commend: java -jar ariafx-0.28.9-jar-with-dependencies.jar

** see [releases](https://github.com/salemebo/Ariafx/releases) for other options, older version


## Browser Plugins:  (need to reimplement)
 - FlashGot for Firefox, is no longer supported due to not compatibility with Firefox Quantum version 57.
 - Aria Port for Chrome,  need to be updated with the latest Chrome API, will be reimplement
 - so, the new plugin will have support with boot Chrome and Firefox Browser, and this will impact the connection between the browser and the app


## try Ariia 
 - CLI and cloud based download manager [Ariia](https://github.com/salemebo/ariia)
i am currently work on this app

**Comment by mx202** [comment]
I struggled so hard to make it work and in the end I succeeded with difficulty and tried it and it was a nice program even though the download speed is a little low and needs to be developed

Also, the `.deb` copy does not work even though it is installed on my Ubuntu 20.04
Therefore, please help you by providing a copy of the program in the format `.deb` and `.flatpak` to make the installation process easy and fast, especially for non-developers

**Comment by mx202** [comment]
I also advise you to continue developing Ariafx because I strongly believe that it will be the elite download software
Trust me because I am sure

**Comment by muhammad-salem** [comment]
> I struggled so hard to make it work and in the end I succeeded with difficulty
- it still work but, need some time for support

> Also, the `.deb` copy does not work even though it is installed on my Ubuntu 20.04
- I tried install it on Ubuntu 20.04, and it did not run with me, that because the version of the default JDK  is 14, it has no javafx support, so in the build will need to build the '.deb' and '.flatpak' with a run-time JVM included 

> it was a nice program even though the download speed is a little low and needs to be developed
 - ya, that is why i developed a new app to speed up the process of downloading and make it easer,
i think make this app work on the desktop platform, is to refactor this app then merge it with the second app Ariia

> I also advise you to continue developing Ariafx because I strongly believe that it will be the elite download software
Trust me because I am sure

- Thanks a lot, :D
